config/routes.rb
Rails.application.routes.draw do
  root 'syobocal#index'
  get '/syobocal/show/:tid', to: 'syobocal#show', as: 'syobocal_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/syobocal_controller.rb
class SyobocalController < ApplicationController
  def index
    # Syobocal Gem を使用してデータを取得
    @result = Syobocal::DB::TitleLookup.get({'TID' => '*', 'Fields' => 'TID,Title'})
  end

  def show
    tid = params[:tid]
    title_info = Syobocal::DB::TitleLookup.get({'TID' => tid}).first
    @title = title_info[:title]
    @short_title = title_info[:short_title]
    @title_yomi = title_info[:title_yomi]
    @title_en = title_info[:title_en]
    @comment = title_info[:comment]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/syobocal_helper.rb
module SyobocalHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SyobocalViewer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/syobocal/index.html.erb
<h1>Syobocal Viewer</h1>

<% @result.each do |title_info| %>
  <div class="title-info" data-tid="<%= title_info[:tid] %>">
    <h2>
      <%= link_to title_info[:title], syobocal_show_path(tid: title_info[:tid]) %>
    </h2>
  </div>
<% end %>

app/views/syobocal/show.html.erb
<h1><%= @title %></h1>

<p>ショートタイトル : <%= @short_title %></p>

<p>タイトル読み : <%= @title_yomi %></p>

<p>タイトル英語 : <%= @title_en %></p>

<p>
  <ul>
    <% @comment.split("\n").each do |line| %>
      <% next if line.blank? || line.start_with?('*') %>
      <% url_match = line.match(/(http:\/\/\S+)/) %>
      <% if url_match %>
        <% url = url_match[1].gsub(/\]/, '') %>
        <li><%= link_to url, url %></li>
      <% else %>
        <li><%= line.gsub(/-/, '').gsub(/:/, '').strip %></li>
      <% end %>
    <% end %>
  </ul>
</p>

<%= link_to 'Back', root_path %>